services:
  lldap:
    image: lldap/lldap:stable
    container_name: lldap
    volumes:
      - lldap_data:/data
    environment:
      - TZ=UTC
      - LLDAP_JWT_SECRET=${LLDAP_JWT_SECRET}
      - LLDAP_ADMIN_PASSWORD=${LLDAP_ADMIN_PASSWORD}
      - LLDAP_LDAP_BASE_DN=${LLDAP_BASE_DN}
    networks:
      - auth_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:17170/api/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    restart: unless-stopped

  lldap-init:
    build:
      dockerfile_inline: |
        FROM alpine:latest
        RUN apk add --no-cache curl jq
        COPY lldap-init.sh /scripts/lldap-init.sh
    depends_on:
      lldap:
        condition: service_healthy
    environment:
      - LLDAP_ADMIN_PASSWORD=${LLDAP_ADMIN_PASSWORD}
      - LLDAP_AUTH_PASSWORD=${LLDAP_AUTH_PASSWORD}
      - BASE_DOMAIN=${BASE_DOMAIN}
      - CADDY_LDAP_BIND_PASSWORD=${CADDY_LDAP_BIND_PASSWORD}
    volumes:
      - ./lldap-init.sh:/scripts/lldap-init.sh
    entrypoint: ["/bin/sh", "/scripts/lldap-init.sh"]
    networks:
      - auth_network

  caddy:
    image: caddy-security:latest
    build:
      dockerfile_inline: |
        FROM caddy:2-builder AS builder
        RUN xcaddy build --with github.com/greenpau/caddy-security@v1.1.18
        
        FROM caddy:2
        COPY --from=builder /usr/bin/caddy /usr/bin/caddy
    container_name: caddy
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./certs:/certs:ro
      - ./caddy:/config
      - caddy_data:/data
      - caddy_config:/config_caddy
    environment:
      - BASE_DOMAIN=${BASE_DOMAIN}
      - CADDY_LDAP_BIND_USERNAME=${CADDY_LDAP_BIND_USERNAME}
      - CADDY_LDAP_BIND_PASSWORD=${CADDY_LDAP_BIND_PASSWORD}
      - LLDAP_BASE_DN=${LLDAP_BASE_DN}
      - CADDY_JWT_SECRET=${CADDY_JWT_SECRET}
    networks:
      - auth_network
      - app_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    depends_on:
      - lldap-init
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - DAC_OVERRIDE

networks:
  auth_network:
    driver: bridge
    internal: true  # This network is not accessible from outside
  app_network:
    driver: bridge   # Allows accessing the docker host from the container

volumes:
  lldap_data:
    driver: local
  caddy_data:
    driver: local
  caddy_config:
    driver: local