theme: dark

# Server configuration
server:
  host: 0.0.0.0
  port: 9091
  path: ""
  asset_path: ""
  headers:
    csp_template: "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self';"

# Log configuration
log:
  level: info
  format: text
  keep_stdout: true
  file_path: /config/authelia.log

# Default redirection URL
default_redirection_url: https://auth.${BASE_DOMAIN}

# JWT Secret
jwt_secret: ${AUTHELIA_JWT_SECRET}
identity_validation:
  reset_password:
    jwt_secret: ${AUTHELIA_JWT_SECRET}

# TOTP Configuration
totp:
  issuer: ${BASE_DOMAIN}
  period: 30
  skew: 1

# WebAuthn Configuration
webauthn:
  display_name: ${BASE_DOMAIN}
  attestation_conveyance_preference: indirect
  user_verification: preferred
  timeout: 60s

# Session Configuration
session:
  name: authelia_session
  domain: ${BASE_DOMAIN}
  same_site: lax
  secret: ${AUTHELIA_SESSION_SECRET}
  expiration: 1h
  inactivity: 5m
  remember_me_duration: 1M
  cookies:
    authentication_cookie:
      domain: ${BASE_DOMAIN}
      authelia_url: https://auth.${BASE_DOMAIN}
      default_redirection_url: https://auth.${BASE_DOMAIN}
  redis:
    host: redis
    port: 6379

# Storage Configuration (SQLite)
storage:
  encryption_key: ${AUTHELIA_STORAGE_ENCRYPTION_KEY}
  local:
    path: /config/db.sqlite3

# Access Control Configuration
access_control:
  default_policy: one_factor
  rules:
    # Public endpoints
    - domain: auth.${BASE_DOMAIN}
      policy: bypass

    # Admin endpoints
    - domain: users.${BASE_DOMAIN}
      policy: two_factor

    # Protected Applications
    - domain: "*.${BASE_DOMAIN}"
      policy: one_factor

# Authentication Backend (LLDAP)
authentication_backend:
  password_reset:
    disable: false
  refresh_interval: 1m
  ldap:
    implementation: custom
    url: ldap://lldap:389
    timeout: 5s
    start_tls: false
    base_dn: ${LLDAP_BASE_DN}
    additional_users_dn: ou=people
    users_filter: (&({username_attribute}={input})(objectClass=person))
    additional_groups_dn: ou=groups
    groups_filter: (member={dn})
    group_search_mode: filter
    user: uid=authelia,ou=people,${LLDAP_BASE_DN}
    password: ${AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD}
    attributes:
      distinguished_name: distinguishedName
      username: uid
      display_name: displayName
      mail: mail
      member_of: memberOf
      group_name: cn

# Notification Configuration (File - for development)
# In production, change to SMTP
notifier:
  disable_startup_check: true
  filesystem:
    filename: /config/notification.txt
  # For production, uncomment and configure SMTP:
  # smtp:
  #   address: 'smtp.example.com:587'
  #   username: 'authelia@example.com'
  #   password: ${SMTP_PASSWORD}
  #   sender: 'Authelia <authelia@example.com>'
